# Generated by Django 5.2.1 on 2025-05-25 15:33

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("inventory", "0002_category_image_product_image"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="category",
            name="image",
        ),
        migrations.RemoveField(
            model_name="product",
            name="image",
        ),
        migrations.AddField(
            model_name="category",
            name="image_url",
            field=models.URLField(
                blank=True, max_length=500, null=True, verbose_name="Image URL"
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="image_url",
            field=models.URLField(
                blank=True, max_length=500, null=True, verbose_name="Image URL"
            ),
        ),
        migrations.AddField(
            model_name="profile",
            name="image_url",
            field=models.URLField(
                blank=True, max_length=500, null=True, verbose_name="Image URL"
            ),
        ),
    ]
