# Generated by Django 5.2.1 on 2025-05-25 15:37

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("inventory", "0003_remove_category_image_remove_product_image_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="length",
            field=models.PositiveIntegerField(help_text="Length in m"),
        ),
        migrations.AlterField(
            model_name="product",
            name="location",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
