# Generated by Django 5.2.1 on 2025-05-25 16:23

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("inventory", "0005_alter_product_length"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="length",
            field=models.DecimalField(
                decimal_places=1, help_text="Length in meters", max_digits=4
            ),
        ),
    ]
