# Generated by Django 5.2.1 on 2025-05-30 17:18

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("inventory", "0002_populate_category_slugs"),
        ("inventory", "0006_alter_product_length"),
    ]

    operations = []
