# Generated by Django 5.2.1 on 2025-05-31 06:46

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("inventory", "0007_merge_20250530_1718"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="product",
            options={"ordering": ["length", "size"]},
        ),
        migrations.AlterModelOptions(
            name="profile",
            options={"ordering": ["name"]},
        ),
        migrations.AddField(
            model_name="product",
            name="size",
            field=models.CharField(
                blank=True,
                help_text="Size dimensions (e.g., '2400x1200mm', '4x8 feet')",
                max_length=100,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="length",
            field=models.DecimalField(
                blank=True,
                decimal_places=1,
                help_text="Length in meters",
                max_digits=4,
                null=True,
            ),
        ),
    ]
