# Generated by Django 5.2.1 on 2025-05-31 14:47

from django.db import migrations, models


def combine_length_size_to_option(apps, schema_editor):
    """
    Combine existing length and size fields into the new option field
    """
    Product = apps.get_model('inventory', 'Product')
    
    for product in Product.objects.all():
        option_value = ""
        
        if product.length:
            # Convert length from decimal to string with proper formatting
            option_value = f"{product.length} m"
        elif product.size:
            # Use the size field as-is
            option_value = product.size
        
        # Save the combined value to option field
        product.option = option_value
        product.save()


def reverse_combine_option_to_length_size(apps, schema_editor):
    """
    Reverse the combination by splitting option back to length and size
    """
    Product = apps.get_model('inventory', 'Product')
    
    for product in Product.objects.all():
        if product.option:
            # Check if it's a length format (ends with " m")
            if product.option.endswith(" m"):
                # Extract the numeric part for length
                try:
                    length_str = product.option.replace(" m", "")
                    product.length = float(length_str)
                    product.size = None
                except ValueError:
                    # If parsing fails, put it in size field
                    product.size = product.option
                    product.length = None
            else:
                # It's a size value
                product.size = product.option
                product.length = None
        
        product.save()


class Migration(migrations.Migration):
    dependencies = [
        ("inventory", "0008_alter_product_options_alter_profile_options_and_more"),
    ]

    operations = [
        # Step 1: Add the new option field
        migrations.AddField(
            model_name='product',
            name='option',
            field=models.CharField(
                max_length=100, 
                help_text="Product option (length, size, or other specifications)", 
                blank=True, 
                null=True
            ),
        ),
        
        # Step 2: Migrate existing data
        migrations.RunPython(
            combine_length_size_to_option,
            reverse_combine_option_to_length_size
        ),
        
        # Step 3: Remove the old fields
        migrations.RemoveField(
            model_name='product',
            name='length',
        ),
        migrations.RemoveField(
            model_name='product',
            name='size',
        ),
    ]
