# Generated by Django 5.2.1 on 2025-05-31 14:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("inventory", "0009_combine_length_size_to_option"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="product",
            options={"ordering": ["option"]},
        ),
        migrations.AddField(
            model_name="product",
            name="category",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="inventory.category",
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="name",
            field=models.CharField(
                blank=True,
                help_text="Product name (required if no profile)",
                max_length=200,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="profile",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="inventory.profile",
            ),
        ),
    ]
