# Generated by Django 5.2.1 on 2025-06-01 13:46

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("inventory", "0011_update_product_structure"),
    ]

    operations = [
        migrations.RenameField(
            model_name="product",
            old_name="location",
            new_name="note",
        ),
    ]
